#!/bin/sh

PRG="$0"

while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
LFR_HOME=`dirname "$PRG"`

# Absolute path
LFR_HOME=`cd "$LFR_HOME/.." ; pwd`
echo "Resolved LFR_HOME: $LFR_HOME"

mkdir -p "$LFR_HOME"/bootstrap/target/osgi/bin
mkdir -p "$LFR_HOME"/bootstrap/target/osgi/bundle
mkdir -p "$LFR_HOME"/bootstrap/target/osgi/conf

cp "$LFR_HOME"/bootstrap/src/main/bin/* "$LFR_HOME"/bootstrap/target/osgi/bin
chmod +x "$LFR_HOME"/bootstrap/target/osgi/bin/*.sh

cp "$LFR_HOME"/bootstrap/src/main/conf/* "$LFR_HOME"/bootstrap/target/osgi/conf

# Most LFR bundles are not special and belong in "bundle"
cp "$LFR_HOME"/target/all/*.jar "$LFR_HOME"/bootstrap/target/osgi/bundle

# Move the startup-related JAR from the "bundle" directory to the "bin" directory
mv "$LFR_HOME"/bootstrap/target/osgi/bundle/com.liferay.cli.bootstrap-*.jar "$LFR_HOME"/bootstrap/target/osgi/bin
mv "$LFR_HOME"/bootstrap/target/osgi/bundle/org.apache.felix.framework-*.jar "$LFR_HOME"/bootstrap/target/osgi/bin

# Build a classpath containing our two magical startup JARs (we look for " /" as per LFR-905)
LFR_CP=`echo "$LFR_HOME"/bootstrap/target/osgi/bin/*.jar | sed 's/ \//:\//g'`
# echo LFR_CP: $LFR_CP

# Store file locations in variables to facilitate Cygwin conversion if needed

LFR_OSGI_FRAMEWORK_STORAGE="$LFR_HOME/bootstrap/target/osgi/cache"
# echo "LFR_OSGI_FRAMEWORK_STORAGE: $LFR_OSGI_FRAMEWORK_STORAGE"

LFR_AUTO_DEPLOY_DIRECTORY="$LFR_HOME/bootstrap/target/osgi/bundle"
# echo "LFR_AUTO_DEPLOY_DIRECTORY: $LFR_AUTO_DEPLOY_DIRECTORY"

LFR_CONFIG_FILE_PROPERTIES="$LFR_HOME/bootstrap/target/osgi/conf/config.properties"
# echo "LFR_CONFIG_FILE_PROPERTIES: $LFR_CONFIG_FILE_PROPERTIES"

cygwin=false;
case "`uname`" in
    CYGWIN*)
        cygwin=true
        ;;
esac

if [ "$cygwin" = "true" ]; then
    export LFR_HOME=`cygpath -wp "$LFR_HOME"`
    export LFR_CP=`cygpath -wp "$LFR_CP"`
    export LFR_OSGI_FRAMEWORK_STORAGE=`cygpath -wp "$LFR_OSGI_FRAMEWORK_STORAGE"`
    export LFR_AUTO_DEPLOY_DIRECTORY=`cygpath -wp "$LFR_AUTO_DEPLOY_DIRECTORY"`
    export LFR_CONFIG_FILE_PROPERTIES=`cygpath -wp "$LFR_CONFIG_FILE_PROPERTIES"`
    # echo "Modified LFR_HOME: $LFR_HOME"
    # echo "Modified LFR_CP: $LFR_CP"
    # echo "Modified LFR_OSGI_FRAMEWORK_STORAGE: $LFR_OSGI_FRAMEWORK_STORAGE"
    # echo "Modified LFR_AUTO_DEPLOY_DIRECTORY: $LFR_AUTO_DEPLOY_DIRECTORY"
    # echo "Modified LFR_CONFIG_FILE_PROPERTIES: $LFR_CONFIG_FILE_PROPERTIES"
fi

# make sure to disable the flash message feature for the default OSX terminal, we recommend to use a ANSI compliant terminal such as iTerm if flash message support is desired
APPLE_TERMINAL=false;
if [ "$TERM_PROGRAM" = "Apple_Terminal" ]; then
	APPLE_TERMINAL=true
fi

# Hop, hop, hop...
#DEBUG=
DEBUG="-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
PAUSE=
#PAUSE="-Dlfr.pause=true"
METADATA_TRACE=
#METADATA_TRACE="-Dlfr.metadata.trace=true"
ANSI="-Dlfr.console.ansi=true"
java $PAUSE $DEBUG $METADATA_TRACE $ANSI -Dis.apple.terminal=$APPLE_TERMINAL $LFR_OPTS -Dorg.osgi.framework.bootdelegation=org.netbeans.lib.profiler,org.netbeans.lib.profiler.\* -Dlfr.args="$*" -DdevelopmentMode=true -Dorg.osgi.framework.storage="$LFR_OSGI_FRAMEWORK_STORAGE" -Dfelix.auto.deploy.dir="$LFR_AUTO_DEPLOY_DIRECTORY" -Dfelix.config.properties="file:$LFR_CONFIG_FILE_PROPERTIES" -cp "$LFR_CP" com.liferay.cli.bootstrap.Main
EXITED=$?
echo LFR exited with code $EXITED
